trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  sourceRegistry: 'repasowebappacr.azurecr.io'
  sourceImage: 'bookapprepaso:1502'
  targetRegistry: 'fisica3.azurecr.io'
  targetImage: 'bookapprepaso:15'

steps:
#- task: DockerInstaller@0
  #inputs:
  #  dockerVersion: 'latest'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc_arm_ErnestoContainers'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az upgrade --yes
      az login --identity
      az acr import --name fisica3.azurecr.io --source bookapprepaso:1502 --image bookapprepaso:15 --registry /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/sourceResourceGroup/providers/Microsoft.ContainerRegistry/registries/sourceRegistry
    #addSpnToEnvironment: true
    #az acr import --name MyRegistry --source docker.io/library/hello-world:latest --image targetrepository:targettag
#az acr import --name MyRegistry --source sourcerepository:sourcetag --image targetrepository:targettag 
#--registry /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/sourceResourceGroup/providers/Microsoft.ContainerRegistry/registries/sourceRegistry
#Import an image from an Azure container registry in a different subscription.